### PR TITLE
Readded support for local sources in CSS

### PR DESCRIPTION
**Pull request by Cortys**
Another stab at the local source support that was added in #41.

This implementation is more flexible. It accepts an arbitrary amount of `local()` font references and thus also works when no locals are provided.

### CODE REVIEW

**Comment by rmpel** [comment]
Connect error also on Roboto Slab. Cause: they don't have 'local' in the font-face definition.

Made a fix in the regular expression, pull request will come soon.

**Comment by rmpel** [comment]
weird. I made a fork, the fork does not have this bug. confused here.

anyways

this is the partial regular expression (with support for local) now

`"\\s*src:\\s*local\\('([^']+)'\\),\\s*local\\('([^']+)'\\),\\s*url\\(([^)]+)\\)[^;]*;",`

this is it fixed 

`"\\s*src:(?:\\s*local\\('([^']+)'\\),)?(?:\\s*local\\('([^']+)'\\),)?\\s*url\\(([^)]+)\\)[^;]*;",`

**Comment by Cortys** [comment]
@rmpel This PR should already fix the bug since it accepts arbitrarily many `local`s (i.e. also none as in Roboto Slab).

**Comment by rmpel** [comment]
Sorry. I see. 
It's very confusing when the fork I make on GH is not the same code as when I install with npm. 
This made me not look closely enough at your PR. 
My bad.

**Comment by iLeonelPerea** [comment]
Hello @rmpel and @Cortys  .. can you please merge this pull request please?

**Comment by rmpel** [comment]
Forgive me if I'm wrong, but I don't think either @Cortys or myself can do that ... this project is maintained by @battlesnake, so _he_ will have to do the merging.

**Comment by battlesnake** [comment]
Ah sorry, I somehow didn't notice the progress on this PR.  Will review.

**Pull request merged**
