### PR TITLE
Add relative path option

### PR DESCRIPTION
**Pull request by Radiergummi**
This commit adds support for the much-requested `relativePaths` option from #20, #13 and #7.  
This should generally work by using `path.relative()`, as long as actual relative paths are passed (`./fonts` or `./css`).   
The option is implemented as a boolean, defaulting to false, so this is no breaking change.

### CODE REVIEW

**Comment by battlesnake** [comment]
Thanks!

**Comment by battlesnake** [comment]
The `README.md` is generated from `README.lmd`, by the `make-docs.sh` script.

Could you apply your changes to the MD file to the LMD file, then I'll regen the docs, npm version bump, merge & publish.

Thanks again for implementing the feature!

**Comment by Radiergummi** [comment]
@battlesnake nope, don't yet - just noticed it doesn't resolve the path to the fonts directory correctly anymore. I'll fix it, update the readme and get back to you. Sorry!

**Comment by battlesnake** [comment]
No problem, thanks for actually contributing :)  Most feature requests I get on here just die after I ask for a PR!

**Comment by Radiergummi** [comment]
Yup, there it is. The code is pretty nested, took a while to wrap my head around it. Easy fix, now that I got it ;)

Should work as expected now. Btw, I'd suggest changing the `var googleWebFonts = require('gulp-google-webfonts');` to `var googleWebFonts = require('../');` in the examples, so it does actually load the included index.js from the repository instead of the npm version. Otherwise the examples won't work before the module is published to npm! :)

**Comment by battlesnake** [comment]
Good idea.  Are you ok to make that change too?

Thanks!

**Comment by Radiergummi** [comment]
Done.

**Comment by battlesnake** [comment]
Merged, thanks.

**Pull request merged**
