### PR TITLE
Support downloading other formats

### PR DESCRIPTION
**Pull request by michaelmior**
It would be nice if other formats such as WOFF2 and TTF could also be downloaded. Seems like this would really just amount to picking a UA string known to be served those fonts. I'd probably be able to hack something together if that sounds reasonable.

### CODE REVIEW

**Comment by battlesnake** [comment]
Sure, as I said last time someone brought this up - send a PR and don't break backwards compatibility :)

**Comment by michaelmior** [comment]
Sorry, should have checked for an existing issue. Seems like backwards compatibility is easily solved by having a format option which defaults to WOFF.

**Comment by battlesnake** [comment]
It's fine, some of the past issues are terribly worded and make my eyes want to bleed, I don't expect you to hunt through all that :) Having an option to select which formats are downloaded/emitted seems like a good idea, thanks in advance :)

**Comment by michaelmior** [comment]
Here's a first pass at this attached. Should be backwards compatible. However, this will produce different output since WOFF2 fonts specify a particular value for `unicode-range`. To keep the code simple, a value for this attribute is now generated for every type and just set to the default when it isn't given.

**Comment by battlesnake** [comment]
Looks good — fix up the coding style then I'll be happy to merge it!  Thanks!

**Comment by michaelmior** [comment]
@battlesnake What in particular do you want fixed up? The style is fine for my tastes and doesn't really seem to deviate from the style of the rest of the code.

**Comment by battlesnake** [comment]
http://pasteboard.co/d2KXUeUZ4.png

I suspect your editor is mixing spaces into the indentation - I can fix it myself, but Github might not recognise you as a contributor if I do it.

**Comment by michaelmior** [comment]
@battlesnake Whoops! Sorry about that. I'm a spaces guy and I didn't notice. Should be good now!

**Comment by battlesnake** [comment]
Thanks a lot, merging!

**Comment by michaelmior** [comment]
Thanks!

**Comment by michaelmior** [comment]
I should note that I didn't deal with EOT or SVG here because I'm not sure what UAs would be served these formats (plus I don't really care about them personally). It should be easy to extend support for these later though.

**Comment by battlesnake** [comment]
I didn't bother with WOFF2 originally because I don't care about it - but when others asked, I told them to send a PR.  It's fine for you to not do EOT/SVG, somebody else can do a PR for those formats if they want them :)

**Pull request merged**
