### PR TITLE
Upgrade to gulp 4.

### PR DESCRIPTION
**Pull request by enavarrocu**

### CODE REVIEW

**Comment by battlesnake** [comment]
Why?

**Comment by enavarrocu** [comment]
This does not work with gulp 4 without those changes.

**Comment by battlesnake** [comment]
That suggests that existing projects using it with Gulp 3 will break then with these changes.  I'll bump the major version on this too.

**Comment by enavarrocu** [comment]
Indeed. Version change should keep back compatibility.

**Pull request merged**
